## Agregar paciente 

POST http://localhost:8089/paciente HTTP/1.1
Content-Type: application/json

{
  "nombrePaciente":"paciente Federico",
  "perosna_idPersona":2,
  "convenio_id_convenio":3
}




### Entregar paciente
GET  http://localhost:8089/paciente HTTP/1.1
Content-Type: application/json


### Obtener paciente segun id 
GET http://localhost:8089/paciente/1 HTTP/1.1
Content-Type: application/json


### Actualizar paciente
PUT http://localhost:8089/paciente/1 HTTP/1.1
Content-Type: application/json

{
  "nombrePaciente":"paciente pedrero",
  "perosna_idPersona":2,
  "convenio_id_convenio":3
}


### Eliminar paciente
DELETE http://localhost:8089/paciente/1 HTTP/1.1
Content-Type: application/json