## Agregar persona 

POST http://localhost:6767/cita_medica HTTP/1.1
Content-Type: application/json

{
    "fecha_cita": "2023-10-10",
    "hora_agendada_cita": "10:00:00",
    "motivo_cita": "consulta de rutina",
    "estado_cita": "pendiente",
    "paciente_id_paciente": 1,
    "medico_id_medico": 1
}




### Entregar persona
GET  http://localhost:6767/cita_medica HTTP/1.1
Content-Type: application/json


### Obtener persona segun id 
GET http://localhost:6767/cita_medica HTTP/1.1
Content-Type: application/json


### Actualizar persona
PUT http://localhost:6767/cita_medica HTTP/1.1
Content-Type: application/json

{
    "fecha_cita": "2023-10-10",
    "hora_agendada_cita": "10:00:00",
    "motivo_cita": "consulta de rutina",
    "estado_cita": "pendiente",
    "paciente_id_paciente": 1,
    "medico_id_medico": 1
}


### Eliminar persona
DELETE http://localhost:6767/cita_medica HTTP/1.1
Content-Type: application/json