#### CREAR CONVENIO
POST http://localhost:7777/convenio_salud HTTP/1.1
content-type: application/json

{
  "nombre_convenio_salud": "Fonasa"
}

#### OBTENER CONVENIOS
GET http://localhost:7777/convenio_salud HTTP/1.1
content-type: application/json

#### ACTUALIZAR CONVENIO
PUT http://localhost:7777/convenio_salud/1 HTTP/1.1
Content-Type: application/json

{
  "nombre_convenio_salud": "Isapre"
}

#### ELIMINAR CONVENIO
DELETE http://localhost:7777/convenio_salud/1 HTTP/1.1
content-type: application/json