## Agregar persona 

POST http://localhost:2020/persona HTTP/1.1
Content-Type: application/json

{
  "run": "6-88886",
  "nombre": "alejandro",
  "apellido_paterno": "montecinos",
  "apellido_materno": "pavez",
  "fecha_nacimiento": "2005-06-15",
  "telefono": "+56912345678",
  "correo": "hola1il.com",
  "contrasenia":"123456789",
  "direccion": "av./////holahola",
  "COMUNA_id_comuna": 1,
  "ROL_id_rol": 1
}




### Entregar persona
GET  http://localhost:2020/persona HTTP/1.1
Content-Type: application/json


### Obtener persona segun id 
GET http://localhost:2020/persona/1 HTTP/1.1
Content-Type: application/json


### Actualizar persona
PUT http://localhost:2020/persona/4 HTTP/1.1
Content-Type: application/json

{
  "run": "6-5555556",
  "nombre": "alejandro",
  "apellido_paterno": "montecinos",
  "apellido_materno":"fedelobo",
  "fecha_nacimiento": "2005-06-15",
  "telefono": "+56912345678",
  "correo": "gmail.com",
  "contrasenia":"555555",
  "direccion": "av./////holahola",
  "COMUNA_id_comuna": 2,
  "ROL_id_rol": 3
}


### Eliminar persona
DELETE http://localhost:2020/persona/3 HTTP/1.1
Content-Type: application/json


### Login Persona

POST http://localhost:2020/persona/login HTTP/1.1
Content-Type: application/json

{
  "correo": "111111@gmail.com",
  "contrasenia": "12345678"
}