#### CREAR ESPECIALIDAD MEDICA
POST http://localhost:8085/especialidadMedica HTTP/1.1
content-type: application/json

{
  "nombre_especialidad_medica": "Esta es una descripcion de prueba"
}

#### OBTENER ESPECIALIDADES MEDICAS
GET http://localhost:8085/especialidadMedica HTTP/1.1
content-type: application/json

#### EDITAR ESPECIALIDAD MEDICA
PUT http://localhost:8085/especialidadMedica/1 HTTP/1.1
Content-Type: application/json

{
  "nombre_especialidad_medica": "Esta es una descripcion de prueba actualizada"
}

#### ELIMINAR ESPECIALIDAD MEDICA
DELETE http://localhost:8085/especialidadMedica/1 HTTP/1.1
content-type: application/json